# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 00:15
from __future__ import unicode_literals

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170207_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=courses.fields.PositionField(default=-1),
        ),
    ]
