# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_mycourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourses',
            options={'verbose_name': 'My courses', 'verbose_name_plural': 'My courses'},
        ),
    ]
