# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
